### ISSUE TITLE
TODO list - 1.1.0

### ISSUE THREAD

**Issue by bpawlik** [bpawlik/duduchinese#1]
- [x] Add text to speech support
- [x] Add "Add sentence to a word" form
- [x] Add learning items to the revision page
- [x] Fix many to many match (e.g. sentences)
- [x] Rename list should change also name in revision item list
- [ ] ~~Add sort by time for list listview.~~
- [x] Enable download and upload of revision list
- [x] Introduce backup and restore mode in the settings
- [x] Display last backup file name / date in the settings
- [x] Display number of revisions under Revisions button
- [x] Add "All" option for new material list
