### ISSUE TITLE
TODO list - 1.2.0

### ISSUE THREAD

**Issue by bpawlik** [bpawlik/duduchinese#5]
- [ ] Add progress bar in the revision page
- [ ] Add selectable "white list" of exercise to the settings page
- [ ] Add "Do not set revisions for these items" checkbox
- [ ] Add "Mark as learnt" in revision details

- [ ] Allow user to upload the latest version of the dictionary (in-device indexing)
- [ ] Add male/female voice selection
- [ ] Add application language selection
- [ ] Add "zoom" by pinching feature, especially to learning section
- [x] For high resolution displays, display chinese characters with larger font size and add stroke gif
- [ ] Multiple windows support, e.g. search / stroke view while learning
- [x] Change English text colour to light gray
- [x] Add sound on wrong answer
